---
- name: Create GCP infrastructure
  hosts: localhost
  gather_facts: false
  vars_files:
    - ../vars/machines.yaml
  tasks:
    - name: Create Jenkins DNS record in Cloudflare
      community.general.cloudflare_dns:
        zone: "{{ cloudflare_zone }}"
        record: "jenkins"
        type: A
        value: "{{ ((instance_files.results | selectattr('item.name', 'equalto', 'jenkins') | first).content | b64decode | from_json)['networkInterfaces'][0]['accessConfigs'][0]['natIP'] }}"
        proxied: true
        api_token: "{{ cloudflare_api_token }}"
      when: not destroy_infrastructure | default(false)